import { test, expect } from "vitest"
import { ConcatenateVectorfields } from "../../src/cards/concatenateVectorfields"
import { dt } from "../../src/cardBase/dataTypes"

const vf1 = dt.vectorfield([dt.vector([1, 1, 1]), dt.vector([1, 1, 1])])
const vf2 = dt.vectorfield([dt.vector([2, 2, 2]), dt.vector([2, 2, 2])])
const vf3 = dt.vectorfield([dt.vector([3, 3, 3]), dt.vector([3, 3, 3])])
const vf4 = dt.vectorfield([dt.vector([4, 4, 4]), dt.vector([4, 4, 4])])
const vf5 = dt.vectorfield([dt.vector([5, 5, 5]), dt.vector([5, 5, 5])])

test("ConcatenateVectorfields concatenates 2 vectorfields", async () => {
    const card = new ConcatenateVectorfields()
    const result = await card.evaluate([vf1, vf2])
    expect(result[0].kind).toBe("vectorfield")
    if (result[0].kind !== "vectorfield")
        throw new Error("Expected vectorfield kind")
    expect(result[0].vectors.length).toBe(4)
    expect(result[0].vectors[0].value.components[0]).toBe(1)
    expect(result[0].vectors[1].value.components[0]).toBe(1)
    expect(result[0].vectors[2].value.components[0]).toBe(2)
    expect(result[0].vectors[3].value.components[0]).toBe(2)
})

test("ConcatenateVectorfields concatenates 3 vectorfields", async () => {
    const card = new ConcatenateVectorfields()
    const result = await card.evaluate([vf1, vf2, vf3])
    expect(result[0].kind).toBe("vectorfield")
    if (result[0].kind !== "vectorfield")
        throw new Error("Expected vectorfield kind")
    expect(result[0].vectors.length).toBe(6)
    expect(result[0].vectors[0].value.components[0]).toBe(1)
    expect(result[0].vectors[1].value.components[0]).toBe(1)
    expect(result[0].vectors[2].value.components[0]).toBe(2)
    expect(result[0].vectors[3].value.components[0]).toBe(2)
    expect(result[0].vectors[4].value.components[0]).toBe(3)
    expect(result[0].vectors[5].value.components[0]).toBe(3)
})

test("ConcatenateVectorfields concatenates 4 vectorfields", async () => {
    const card = new ConcatenateVectorfields()
    const result = await card.evaluate([vf1, vf2, vf3, vf4])
    expect(result[0].kind).toBe("vectorfield")
    if (result[0].kind !== "vectorfield")
        throw new Error("Expected vectorfield kind")
    expect(result[0].vectors.length).toBe(8)
    expect(result[0].vectors[0].value.components[0]).toBe(1)
    expect(result[0].vectors[1].value.components[0]).toBe(1)
    expect(result[0].vectors[2].value.components[0]).toBe(2)
    expect(result[0].vectors[3].value.components[0]).toBe(2)
    expect(result[0].vectors[4].value.components[0]).toBe(3)
    expect(result[0].vectors[5].value.components[0]).toBe(3)
    expect(result[0].vectors[6].value.components[0]).toBe(4)
    expect(result[0].vectors[7].value.components[0]).toBe(4)
})

test("ConcatenateVectorfields concatenates 5 vectorfields", async () => {
    const card = new ConcatenateVectorfields()
    const result = await card.evaluate([vf1, vf2, vf3, vf4, vf5])
    expect(result[0].kind).toBe("vectorfield")
    if (result[0].kind !== "vectorfield")
        throw new Error("Expected vectorfield kind")
    expect(result[0].vectors.length).toBe(10)
    expect(result[0].vectors[0].value.components[0]).toBe(1)
    expect(result[0].vectors[1].value.components[0]).toBe(1)
    expect(result[0].vectors[2].value.components[0]).toBe(2)
    expect(result[0].vectors[3].value.components[0]).toBe(2)
    expect(result[0].vectors[4].value.components[0]).toBe(3)
    expect(result[0].vectors[5].value.components[0]).toBe(3)
    expect(result[0].vectors[6].value.components[0]).toBe(4)
    expect(result[0].vectors[7].value.components[0]).toBe(4)
    expect(result[0].vectors[8].value.components[0]).toBe(5)
    expect(result[0].vectors[9].value.components[0]).toBe(5)
})
