import { test, expect } from "vitest"
import { dt, Vector, type DataTypeOf } from "../../src/cardBase/dataTypes"
import { VoronoiDiagram } from "../../src/cards/voronoiDiagram"

test("returns a vectorfield and all original points are in that field", async () => {
    const points: DataTypeOf<"vector">[] = []
    for (let i = 0; i < 10; i++) {
        points.push(
            dt.vector([
                Math.floor(Math.random() * 200) - 100,
                Math.floor(Math.random() * 200) - 100,
            ]),
        )
    }

    const card = new VoronoiDiagram()
    const voronoi_result = await card.evaluate([dt.vectorfield(points)])

    const cell_centers_data = voronoi_result.find(
        (r): r is DataTypeOf<"vectorfield"> => r.kind === "vectorfield",
    )
    const regions_data = voronoi_result.find(
        (r): r is DataTypeOf<"shape"> => r.kind === "shape",
    )

    expect(cell_centers_data).toBeDefined()
    expect(regions_data).toBeDefined()
    expect(
        regions_data!.value.every(
            (curve) => typeof curve.getValue === "function",
        ),
    ).toBe(true)
    const cell_centers = cell_centers_data!.vectors

    let missing_point = false
    for (let gi = 0; gi < cell_centers.length; gi++) {
        let found = false
        for (let pi = 0; pi < points.length; pi++) {
            if (cell_centers[gi].value.equals(points[pi].value)) {
                found = true
                break
            }
        }
        if (!found) {
            missing_point = true
            break
        }
    }
    expect(missing_point).toEqual(false)
})
test("Compare result to known voronoi diagram", async () => {
    const known_graph_data = dt.graph()
    const known_graph = known_graph_data.value
    known_graph.nodes = [
        new Vector([-20.278935282108385, 14.179532567007875]),
        new Vector([20.17116051413725, 44.43055613955862]),
        new Vector([-15.82545085599129, 93.06873947235246]),
        new Vector([-19.52674025926928, 93.06873947235246]),
        new Vector([-31.0445302539949, 15.693962457980483]),
        new Vector([36.439726428495476, 93.06873947235246]),
        new Vector([44.66815690095877, 46.38931993299391]),
        new Vector([49.32055676780805, 45.724530512388505]),
        new Vector([69.4329570370425, 93.06873947235246]),
        new Vector([-48.1875180319295, -88.46428221370056]),
        new Vector([89.18131870208049, -88.46428221370056]),
        new Vector([89.18131870208049, -64.36574003055243]),
        new Vector([25.046496709556543, -37.89926395848073]),
        new Vector([-48.1875180319295, -81.00296474194158]),
        new Vector([22.54683285908564, 45.45397133781147]),
        new Vector([17.373021733270086, 93.06873947235246]),
        new Vector([-6.144042597527466, -1.5328290220403602]),
        new Vector([79.22270922158464, 22.604049359600577]),
        new Vector([-48.1875180319295, 13.393533477960961]),
        new Vector([-48.1875180319295, 93.06873947235246]),
        new Vector([89.18131870208049, 93.06873947235246]),
        new Vector([89.18131870208049, 15.248737559983354]),
    ]
    known_graph.edges = [
        [
            null,
            1,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            1,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            1,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            1,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
        ],
        [
            1,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            1,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
        ],
        [
            null,
            1,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            1,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
        ],
        [
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            1,
        ],
        [
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
        ],
        [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            null,
            null,
            null,
            1,
            null,
            null,
            1,
            null,
        ],
    ]
    const input_points = dt.vectorfield([
        dt.vector([-7.704667186072271, 67.8292504256057]),
        dt.vector([45.02416376380245, 83.06873947235246]),
        dt.vector([-0.8592891587297089, -78.46428221370056]),
        dt.vector([5.939419479255463, 77.92709642926201]),
        dt.vector([34.73729289877926, 11.078068202123674]),
        dt.vector([-38.1875180319295, 72.36684120170466]),
        dt.vector([79.18131870208049, 68.55836138666422]),
        dt.vector([31.791960058154956, 80.73622828725541]),
        dt.vector([35.28813325449357, 9.129868803895675]),
        dt.vector([-22.99391883092443, -40.85712166258535]),
    ])
    const card = new VoronoiDiagram()
    const voronoi_result = await card.evaluate([input_points])

    const graph_data = voronoi_result.find(
        (r): r is DataTypeOf<"graph"> => r.kind === "graph",
    )
    expect(graph_data).toBeDefined()
    const graph = graph_data!.value

    expect(graph.nodes.length).toEqual(known_graph.nodes.length)
    let nodes_equal = true
    for (let i = 0; i < graph.nodes.length; i++) {
        if (!graph.nodes[i].equals(known_graph.nodes[i])) {
            nodes_equal = false
            break
        }
    }
    expect(nodes_equal).toEqual(true)
    let edges_equal = true
    for (let j = 0; j < graph.nodes.length; j++) {
        for (let i = 0; i < graph.nodes.length; i++) {
            if (graph.edges[i][j] != known_graph.edges[i][j]) {
                edges_equal = false
                break
            }
        }
    }
    expect(edges_equal).toEqual(true)
})
